version: "3.9"
services:
  db:
    image: postgres:16
    environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: app
    POSTGRES_DB: gonogo
  ports: ["5432:5432"]
  volumes:
  - pgdata:/var/lib/postgresql/data
  api:
    build: ./docker
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    environment:
      DB_URL: postgresql+psycopg://app:app@db:5432/gonogo
      NWS_CONTACT: ${NWS_CONTACT}
        API_SECRET: ${API_SECRET}
    volumes:
      - ./:/code
    working_dir: /code
    depends_on: [db]
    ports: ["8000:8000"]
  ui:
    build: ./docker
    command: streamlit run app/ui/dashboard.py --server.port=8501 --server.address=0.0.0.0
    environment:
      API_BASE: http://api:8000
    volumes:
      - ./:/code
    working_dir: /code
    depends_on: [api]
    ports: ["8501:8501"]
volumes:
  pgdata: {}